### PR TITLE
Add helpers

### PR DESCRIPTION
**Pull request by oswald2**
Hello, I started developing some plugins based on lv2_raw (you can have a look at https://github.com/oswald2/lv2plugins, currently the older version of the simple amplifier from the lv2_raw repository (with pointers), a port of the EQ from ZynAddSubFX (rusteq) and now the working midigate from the lv2 SDK). I am slowly trying to get up with LV2 development step by step (and if time allows).

Anyway, I added some of the util functions for Atoms and also a bit of the MIDI stuff I needed for the midigate. Please have a look it you find them useful.

lg,
Michael

### CODE REVIEW

**Comment by poidl** [comment]
Wow, thanks that looks awesome! I'm excited, this is the first pull request I received on github. I will have to read up in the manual on how to process this. 

_EDIT: I just saw there was a previous [pull request by artfwo](https://github.com/poidl/lv2_raw/commit/c02e48b88353e612d480d1847fee9f1a39cf3e50), I forgot about that :)_

Below are a couple of points we will have to consider. Take this with a grain of salt, I have little experience in programming, particularly Rust and C:

- You added functions from [LV2's `util.h`](http://lv2plug.in/ns/ext/atom/util.h) into `atom.rs`, which "corresponds" to [`atom.h`](http://lv2plug.in/ns/ext/atom/atom.h). I use quotes because there is no technical reason why the file structure of the Rust crate must reflect that of  the C project, but in terms of usability it would be nice have a similar structure. There are probably good reasons why the C project is structured the way it is. Having said that, there is no `util.rs` in this crate, which (1) contradicts what I just said, and (2) may be the reason why you put it into `atom.rs` in the first place.

- I'm trying to separate low-level stuff from high-level stuff:
  - Low-level: The glue between a Rust and C app, the part where Rust will basically look like a verbatim translation of C-code. Typically that's non-idomatic "not true" Rust, but necessary to access the C world. Type aliases for raw pointers, `struct` definitions, `extern "C" fn` declarations passed to the host, etc.
  - High-level: "true" Rust. See [this issue](https://github.com/poidl/lv2/issues/1), and a [question on stackoverflow](http://stackoverflow.com/questions/40944524/how-does-one-design-a-plugin-interface-for-digital-audio-workstation-hosts-in-pu). That's why I have the [separate crate called `lv2`](https://github.com/poidl/lv2), which is supposed to be high-level.

  One could argue that the functions defined in `util.h` should not be part of this low-level crate, because it's not absolutely necessary (AFAIK) to use them in Rust code. Note also the comment in `util.h`:

  > This header is non-normative, it is provided for convenience.
  > 

  "Convenience" belongs into a high-level crate, and ideally these convenient functions are idiomatic Rust to make them really convenient to use in Rust code. I saw you are already going in that direction, e.g. your `lv2_atom_sequence_foreach<F>` looks very Rusty from what I can tell, that's awesome. I wasn't sure how to do that. But I'd prefer putting it into [the `lv2` crate](https://github.com/poidl/lv2).

I'm not sure if that makes sense, I little experience. I noticed that the "separation of concerns" is not consistent in LV2 either. For example,

- [lv2core](https://github.com/drobilla/lv2/tree/master/lv2/lv2plug.in/ns/lv2core) has [`lv2.h`](https://github.com/drobilla/lv2/blob/master/lv2/lv2plug.in/ns/lv2core/lv2.h) which contains no inline (header-only) function, and [`lv2_util.h`](https://github.com/drobilla/lv2/blob/master/lv2/lv2plug.in/ns/lv2core/lv2_util.h), which has *only* function.
- In [ext/atom](https://github.com/drobilla/lv2/tree/master/lv2/lv2plug.in/ns/ext/atom) same thing, `util.h` contains only inline functions or preprocessor directives for loops.
- In [ext/event](https://github.com/drobilla/lv2/blob/master/lv2/lv2plug.in/ns/ext/event) similar with different terminology, there is `event.h` and `event-helpers.h`, although there is also a struct `LV2_Event_Iterator`.

On the other hand, e.g. in [`ext/midi`](https://github.com/drobilla/lv2/blob/master/lv2/lv2plug.in/ns/ext/midi) there is no separation.

Phew, that was verbose.

What do you think, should there be a separation of Rust LV2 crates?

**Comment by poidl** [comment]
One more thing to read is this [cargo doc](http://doc.crates.io/build-script.html#-sys-packages). The reason I didn't call it `lv2-sys` is because it doesn't pull any dependencies, but maybe that was a mistake.

**Comment by oswald2** [comment]
It's also my first pull request :) And my first Rust project.

With regards to to the utils.rs: yes, I agree, that would make it easier for people coming from the C API to adapt. I will do that for the next commits.

While I agree completely, it is very difficult to separate at least some of the  things. LV2 is a lot callback driven and much worse: it has a hell lot of features. For example, how to define a general Rust structure where different ports and features can be added on demand according to the ttl file in a generic way, that has no or very low overhead? While it is doable (I come mainly from C++ and Haskell side and especially on the Haskell side, it is definitely doable, but currently my knowledge of Rust is still lacking), I am not sure how much overhead this would introduce. As LV2 should be hard real time capable, overhead is probably unwanted.
So, for me it really would make sense, to have a simple low-level translation crate, which can be unsafe (there are unsafe functions in the std library anyway), but fast. And of course it makes sense to provide a higher level crate which is more idomatic Rust and probably doesn't have unsafe functions. The same has been done on the Haskell side for e.g. OpenGL, there are several low level direct translations which are fast, and some more convenient, idiomatic wrappers.

Having said that, concerning e.g. the utility functions in utils.h: they are still low level with raw pointer operations as I just translated them directly from C. I don't know a more Rust idiomatic way, the only thing I could imagine which would work and would be safe is treat e.g. the Atom Sequences as a byte stream and parse the results into a native Rust Syntax tree or some sort of container. 
So that is the reason, I added them there, as high level utility functions would probably provide iterator access, trait implementations or other things. I am a bit unsure of how to implement a higher level API, so I think this will need some experimentation.
 
`lv2_atom_sequence_foreach<F>` would be a possible example for putting to the higher level crate, in that you are completely right, but also it would be very handy to have, if you just use the low level crate, as it is a quite essential function. That's the reason I kept it there. 

So maybe the question is, where is the division line of low- and high-level crate? I would see it like that, that the low level crate should be complete in the sense that you could access all LV2 functionality and the high-level crate could build on that to provide a Rust idiomatic interface. How is your view on this?

For the implementation of it: that's the way I would do it in Haskell (providing a closure), so I thought I try that in Rust also. The downside is, at least for the midigate plugin with the concrete closure used there, that the control port for the LV2 Atom Sequence has to be *mut instead of *const, even if it is only read.

Anyway, I noticed later, that for the simple amplifier there were changes to move from the pointers to Rust references, which I first tried and then abandoned for some reason I don't remember (probably bounced too much against the borrow checker). There should be a way to handle this more nicely, so I will study this implementation.

Also my first goal was to get the plugins working :) and get a feel for the functionality of the LV2 API. I think if I better understand it, it will be easier to get an idea for a clean high level API. And while I keep looking for possible abstractions, I still have to wrap my head around the C API (e.g. currently the variadic, printf style parameters are giving me a headache while implementing the Metronom plugin from the LV2 examples).
But i had just the thought, that I could have a look at the JUCE API, which also covers LV2 (but in C++). Maybe there are some ideas to follow?

As for the -sys crate: I am also not sure. There is no library to link to, it is just a header-only API, so I would have to take a closer look on what exactly -sys crates do (yeah, it's still my first Rust project).

Anyway, I am currently working on the Metronom, trying to get it working. I will have a look at the more high level lv2 crate (I must admit, I haven't done this yet), to get a better understanding of it.

**Comment by oswald2** [comment]
So for proceeding: i did my work on a branch. So I propose, I continue to work on my local forked repository on that branch. If you want to pull my changes, it would be probably better, to keep them on that separate branch first as it is still work in progress and possibly until we together find a way for the API that is satisfying for all.

**Comment by poidl** [comment]
> So maybe the question is, where is the division line of low- and high-level crate? I would see it like that, that the low level crate should be complete in the sense that you could access all LV2 functionality and the high-level crate could build on that to provide a Rust idiomatic interface.

Yes good question. Agreed, it should be complete in terms of functionality. Anything else could be rather confusing for users, as they probably expect a *low-level and complete* mirror of LV2. If the helper stuff is part of LV2, then that should also be the case for the low-level crate. 

I will pull the changes next weekend over to my lv2_raw and remove the corresponding stuff from my lv2 repo. Not entirely sure yet about `lv2_atom_sequence_foreach<F>`, maybe there is an alternative closer to C? I'll think about it next week...

**Comment by poidl** [comment]
I get an error in the `add_helpers` branch

```
Compiling lv2_raw v0.1.0 (file:///home/stefan/programs/oswald2/lv2_raw)
error[E0252]: a value named `LV2_MIDI__ACTIVESENSE` has already been imported in this module
  --> src/lib.rs:17:9
   |
14 | pub use atom::*;
   |         -------- previous import of `LV2_MIDI__ACTIVESENSE` here
...
17 | pub use midi::*;
   |         ^^^^^^^^ already imported

error[E0252]: a value named `LV2_MIDI__AFTERTOUCH` has already been imported in this module
  --> src/lib.rs:17:9
   |
14 | pub use atom::*;
   |         -------- previous import of `LV2_MIDI__AFTERTOUCH` here
...
17 | pub use midi::*;
   |         ^^^^^^^^ already imported

error: aborting due to 2 previous errors

error: Could not compile `lv2_raw`.
```

**Comment by poidl** [comment]
Also, I noticed that the run() function in your metronome is commented out. Did you get the metronome working? The reason I looked into it is because it uses the atom sequences:

I was wondering if one could implement Rust's iterator trait for the sequences. Have you looked into that? See [here](https://doc.rust-lang.org/book/iterators.html). I'd like to try that. But I can still merge your stuff before that (if it compiles).

**Comment by oswald2** [comment]
Yeah, there is still the function with variadic parameters missing in porting, the metronome is not working. I had a lot of implementation to do this week in my job, so I haven't had time. But on this weekend I will have a look on the issues.

I also had iterators in mind and I have some rough ideas on getting them to work. Also a few ideas for the more high level interface, but still need to try them out. Anyway, I will have a look in the next days.

**Comment by oswald2** [comment]
Ok, issue should be fixed. I did also some renaming to get rid of some warnings because of Rust naming conventions.

Also the metronome is working now! After getting it to compile, it worked on the first try, even with this messy low level code! That's really like in Haskell, getting to really like Rust...

**Comment by poidl** [comment]
Awesome, huge contribution! Thanks!

>  I did also some renaming to get rid of some warnings because of Rust naming conventions.

Nice! I could imagine that was a lot of typing...

Let me know if you think this is ready for pushing to crates.io.

Some points to consider for the future:

I noticed that you have safe `pub fn` functions that take a reference (e.g. `lv2_midi_is_voice_message`). I haven't thought about this in depth, and for now I don't see a problem with it. But could it be that a dangling pointer ends up in there? If yes, perhaps it's better to declare an `unsafe fn` that takes a raw pointer, at least in the low-level crate?

Wishlist for the future:

- Figure out division line between low- and high-level crate
  - Preliminary goal: provide all functionality of LV2 while keeping it low-level
- Check if it's possible/desirable to implement Iterator trait for the atom sequences
- Check if low-level crate functions should be allowed to accept &-references as argument (instead of raw pointers), making them inherently safe. There are three options I can think of:
  - declaring a `pub fn` and accepting &-references: implies that everything is assumed to be safe a priori
  - declaring a `pub fn` and accepting raw pointers: implies that (probably) an `unsafe` block is used within that function, but the crate exposes a function it guarantees to be safe.
  - declaring a `pub unsafe fn` and accepting raw pointers: let the crate user worry about guaranteeing for safety (the exposed function can only be used in an `unsafe` block)

**Comment by poidl** [comment]
Hmm, I guess it should be either

> declaring a `pub fn` and accepting &-references: implies that everything is assumed to be safe a priori

or 

> declaring a `pub unsafe fn` and accepting raw pointers: let the crate user worry about guaranteeing for safety (the exposed function can only be used in an unsafe block)

It's because having a safe function that accepts a raw pointer looks kind of inconsistent, doesn't it? The data type "raw pointer" is there precisely because it's unsafe.

**Comment by poidl** [comment]
Updated wishlist for the future:

- Figure out division line between low- and high-level crate
  - Preliminary goal: provide all functionality of LV2 while keeping it low-level
- Check if it's possible/desirable to implement Iterator trait for the atom sequences
- Check if low-level crate functions should be allowed to accept &-references as argument (instead of raw pointers), making them inherently safe. There are three options I can think of:
  - declaring a `pub fn` and accepting &-references: implies that everything is assumed to be safe a priori
  - declaring a `pub unsafe fn` and accepting raw pointers: let the crate user worry about guaranteeing for safety (the exposed function can only be used in an `unsafe` block)

**Comment by poidl** [comment]
One more thing: your contributions don't show up on my github page. If that's intentional, that's fine. If not, could it be because your email address is not linked to your gh account?

**Comment by oswald2** [comment]
> Awesome, huge contribution! Thanks!

Glad to help!

> > I did also some renaming to get rid of some warnings because of Rust naming conventions.
> Nice! I could imagine that was a lot of typing...

Not really. I actually use VS Code and you can get pretty far with block mode and multiple cursor feature.

> Let me know if you think this is ready for pushing to crates.io.

In principal yes, but there are still things missing: Atom Tuples and I haven't had a look at the GUI stuff at all. But for an intermediate release it should be ok.

> I noticed that you have safe pub fn functions that take a reference (e.g. lv2_midi_is_voice_message). I  haven't thought about this in depth, and for now I don't see a problem with it. But could it be that a dangling pointer ends up in there? If yes, perhaps it's better to declare an unsafe fn that takes a raw pointer, at least in the low-level crate?

From the Rust side it should be pretty ok. The thing is, we can't control the C side (what the Host provides). Until now, this did really work quite well, in fact I am quite surprised on how well this low level pointer stuff works in Rust (I could tell you stories about pointer issues in the mission control system I work on, you would not believe...)

> Figure out division line between low- and high-level crate

I think, this will need more considerations until this can be settled. I did a first test of an (unsafe) iterator implementation. If you are interested, you can have a look at the "iterator" branch in my fork of the lv2_raw and also the same branch in my plugins, where I converted the MidiGate to iterator style. I am not fully happy with it, I couldn't get a for loop working with it yet. Also I would prefer working with references instead of pointers, so I think this is the next step on my side. Generally, I will now have a look if we can provide interfaces with references, I started to have a brief look on the high level lv2 crate and how things are done there.

I think iterators would then belong to the higher level crate, to implement them properly, there is a single type needed for a result, so probably an enum which encapsulates all possible Atom and an enum providing Rust-idiomatic access to AtomEvents would be cool. But this would need to operate on references only, since Enums are not binary compatible with casted Atom pointers and this would mean copying when not using references. 

Long speek short: still not sure, if the low level interface should really provide interfaces on raw pointers or not.

> Preliminary goal: provide all functionality of LV2 while keeping it low-level

Yup, second that.

> * Check if it's possible/desirable to implement Iterator trait for the atom sequences

Possible, but the current try is a bit awkward. Also I have no idea, if to put iterators into the low level crate or high level crate. In the low level crate, the other APIs probably need update to references, in the higher level crate we need to put Iterator implementations in other modules than the data types, which is also a bit awkward. Hm...

>  * Check if low-level crate functions should be allowed to accept &-references as argument (instead of raw pointers), making them inherently safe. There are three options I can think of:
>    * declaring a pub fn and accepting &-references: implies that everything is assumed to be safe a priori
>    * declaring a pub unsafe fn and accepting raw pointers: let the crate user worry about guaranteeing for safety (the exposed function can only be used in an unsafe block)

Exactly. Still not sure about the best approach.

> One more thing: your contributions don't show up on my github page. If that's intentional, that's fine. If not, could it be because your email address is not linked to your gh account?

Could be because of a setting in my profile (I think I saw a checkbox for this). I enabled it now, so I hope it is fine now.

**Comment by oswald2** [comment]
Hm, I just noticed, that I need to check some things. It could be, that if you use references, the compiler optimizes away access to them, even when the value of the underlying pointer changes. Maybe we need something like [volatile_cell](https://www.reddit.com/r/rust/comments/40ewem/what_is_the_rust_equivalent_for_cs_volatile/)  for the controls?

**Comment by poidl** [comment]
Interesting, can you give a specific example? Did you stumble across this
with any of your plugins? I plan to try them out next weekend.

**Comment by oswald2** [comment]
I changed the iterator to work with references and the plugin (midigate) crashed with segmentation violations. It works properly with an iterator with pointers. Valgrind reported uninitialized memory access. I then abandoned the implementation (it is also not in git). My suspicion is, that Rust has to always read pointers when they are dereferenced, since it has no information about the object they point to, while with References and lifetimes it can sometimes optimize out accesses. Not sure, but maybe something in that direction. It looked like it kept a reference to a dead pointer, though it shouldn't have. 

Another try I want to do is just using pointers internally and only convert them to references for the current immediate output, but yesterday I did run into some lifetime issues I am not quite sure how to resolve. 

So it could be, that volatile_cell would be a better approach, since it seems to encapsulate raw pointers but provide a nicer interface and ensures that they are not optimised out. In principal, this would treat the C part as "hardware". I'll have a look at how the low level projects like zinc, redox and so on handle their things, maybe there is something to learn.

I also started with the sampler plugin yesterday and added some new files (worker, parameters, patch) but now I am stuck on libsndfile because the rsndfile crate is in alpha state and uses nightly-only features (Uniqe pointer). I need to investigate options to continue, as my ultimate goal would be something like a wavetable synthesizer and sndfile is the quasi standard for wave loading/storing.

I tried the plugins from within Carla (it can rescan for the .ttl files and is quick to start/stop if a new dynlib is copied over the old one). I then routed tracks from Ardour to it to test them (exception was the metronome, which I ran directly in Ardour with tempo changes to see if that works: it does). Ardour unfortunately needs to be restarted every time you change a plugin, even if you rescan from the preferences. Took a time to find that out...

**Comment by poidl** [comment]
Thanks for the update, sounds great! Seems like you made a lot of progress.
I'll try to wrap my head around this next weekend and give more feedback.

**Comment by poidl** [comment]
I tried to implement the iterator, the following (in your rustmidigate) works now:

```
unsafe {
    let sequence = &*((*gate).control);
    for ev in sequence {
        let evp = ev as *const LV2AtomEvent;
        if (*ev).body.mytype == gate.midi_event {
            let msg_raw = evp.offset(1) as *const u8;
            let msg = std::slice::from_raw_parts(msg_raw, (*ev).body.size as usize);
            match lv2_midi_message_type(msg) {
                LV2MidiMessageType::LV2MidiMsgNoteOn => { 
                        gate.n_active_notes += 1;
                        println!("NOTE_ON");
                    },
                LV2MidiMessageType::LV2MidiMsgNoteOff => {
                        gate.n_active_notes -= 1;
                        println!("NOTE_OFF");
                    },
                LV2MidiMessageType::LV2MidiMsgPgmChange => {
                        println!("PGM_CHG");
                        if (msg[1] == 0) || (msg[1] == 1) { gate.program = msg[1] as u32; }
                    },
                _ => return
            }   
        }

        let frames = (*ev).time_as_frames();
        gate.write_output(offset, frames as usize - offset as usize);
        offset = frames as isize;
    };
}
 
```

See [this commit in lv2_raw](https://github.com/poidl/lv2_raw/commit/a01e40be04700cc8f91d6cb566839d676db76097). It may not be the correct way to do it, I'll try to improve it. But it's a start, and it seems to work with the plugin.

**Comment by oswald2** [comment]
Cool! Maybe I did see this a bit too complicated. 

I also did a bit experimentation on the LV2AtomObject which is used in the Metronome. I created an Iterator for it but then wanted (as an alternative to the lv2_atom_object_get function) also an iterator adapter to be able to filter for some object properties, but I can't get it to compile. 
I think I will pause this in a branch and then continue with the sample plugin.

**Comment by poidl** [comment]
Sounds good. I guess I'm not going to push this to crates.io right away, but instead wait a couple of weeks in case we encounter any errors with the latest changes, or you decide you want to add new features. If I don't hear from you I'll package it in a couple of weeks.

**Comment by poidl** [comment]
I just published it on crates.io. I renamed the modules to make the documentation look more consistent, possibly causing things to break. But should be quick to fix. [See here](https://docs.rs/lv2_raw/0.2.0/lv2_raw/).

**Comment by oswald2** [comment]
Cool! Sorry, I am in the middle of a music production and also had some private stuff to do, so I haven't had the chance to move on yet.

**Pull request merged**
